name = "smle-click-tracker"
main = "src/worker.ts"
compatibility_date = "2026-01-23"

kv_namespaces = [
  { binding = "CLICKS", id = "103b765eda8a4faba6bf0ac2986874c6" },
  { binding = "CLICKS_ARCHIVE", id = "00000000000000000000000000000000" }
]

[r2_buckets]
binding = "CLICKS_SNAPSHOTS"
bucket_name = "click-snapshots"
[triggers]
crons = ["0 3 * * *"]
