name = "smle-click-tracker"
main = "src/worker.ts"
compatibility_date = "2026-01-23"
workers_dev = false
preview_urls = false

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1

[[analytics_engine_datasets]]
binding = "ANALYTICS_ENGINE"
dataset = "analytics_events"

[vars]
ANALYTICS_SITE = "startmyloveengine"
ANALYTICS_ENGINE_DATASET = "analytics_events"
ANALYTICS_ENGINE_ACCOUNT_ID = "cc228d085f9d2bc113bc0a78dd2ea537"
SITE_MAP_JSON = "{\"smle.mocha.app\":\"startmyloveengine\",\"go.startmyloveengine.com\":\"startmyloveengine\",\"startmyloveengine.com\":\"startmyloveengine\",\"dave-blake.com\":\"dave-blake.com\",\"www.dave-blake.com\":\"dave-blake.com\",\"main.dave-blake.com\":\"dave-blake.com\",\"preview.dave-blake.com\":\"dave-blake.com\",\"staging.dave-blake.com\":\"staging.dave-blake.com\"}"
SITE_ALLOWLIST = "startmyloveengine,dave-blake.com,staging.dave-blake.com"
ANALYTICS_CACHE = "1"
ALLOW_UNAUTH_STATS = "0"

[env.production]
name = "smle-click-tracker"
route = "go.startmyloveengine.com/*"
[env.production.vars]
ANALYTICS_SITE = "startmyloveengine"
ANALYTICS_ENGINE_DATASET = "analytics_events"
ANALYTICS_ENGINE_ACCOUNT_ID = "cc228d085f9d2bc113bc0a78dd2ea537"
SITE_MAP_JSON = "{\"smle.mocha.app\":\"startmyloveengine\",\"go.startmyloveengine.com\":\"startmyloveengine\",\"startmyloveengine.com\":\"startmyloveengine\",\"dave-blake.com\":\"dave-blake.com\",\"www.dave-blake.com\":\"dave-blake.com\",\"main.dave-blake.com\":\"dave-blake.com\",\"preview.dave-blake.com\":\"dave-blake.com\",\"staging.dave-blake.com\":\"staging.dave-blake.com\"}"
SITE_ALLOWLIST = "startmyloveengine,dave-blake.com,staging.dave-blake.com"
ANALYTICS_CACHE = "1"
ALLOW_UNAUTH_STATS = "1"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS_ENGINE"
dataset = "analytics_events"
